apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: hello-pipeline
spec:
  params: 
    - name: message
  tasks:
  - name: hello 
    taskRef: 
      name: echo 
    params: 
      - name: message
        value: "$(params.message)"
---
apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata: 
  name: cd-pipeline 
spec: 
  params: 
    - name: repo-url 
      type: string 
      description: the git repository URL 
    - name: branch 
      type: string 
      description: the git branch to checkout 
      default: "master"
  tasks: 
    - name: clone 
      taskRef:
        name: checkout 
      params: 
        - name: repo-url
          value: $(params.repo-url)
        - name: branch 
          value: $(params.branch)
        - name: deleteExisting 
          value: "true"

    - name: lint 
      taskRef: 
        name: echo 
      params:
        - name: message
          value: "Calling Flake8 linter..."
      runAfter: 
        - clone

    - name: unit-test 
      taskRef:
        name: echo 
      params: 
        - name: message 
          value: "Running unit tests with PyUnit..."
      runAfter:
        - lint

    - name: build 
      taskRef:
        name: echo 
      params: 
        - name: message
          value: "Building image for $(params.repo-url)..."
      runAfter:
        - unit-test

    - name: deploy 
      taskRef:
        name: echo 
      params:
        - name: message 
          value: "Deploying $(params.branch) branch of $(params.repo-url)"
      runAfter: 
        - build 
  
      