name : CI workflow 

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build: 

    runs-on: ubuntu-latest

    container: 
      image: python:3.9-slim
    
    steps:
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Install dependencies
    run: | 
      python -m pip install --upgrade pip
      pip install -r requirements.txt

    - name: Lint with flake8 
    run: | 
      # check for syntax errors 
      flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
      # run all the available checks on the service folder 
      flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run unit tests with nose 
    run: 
      nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

